### ISSUE TITLE
Filtern muss sofort ersichtlich sein

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#1]
Es ist für den user nicht immer sofort ersichtlich, daß er filtert. wird jetzt z.b. nach "concept" gefiltert, passiert erstmal nix (sichtbares).

mögliche lösungen:
- nach betätigen des filters wird der user zum 1. case der filterung geschickt
- wenn die cases nach filterung nicht verschwinden und alle bestehen bleiben sollen sie besser sichbar sein, so daß die wand nicht so schwarz wirkt
- nicht relevante cases verschwinden wirklich. falls dann "löcher" in der wand entstehen entstehen wäre das ok

-> habe auf performance issues beim verschwinden der cases hingewiesen
-> lösung mit den blöcken wurde als gut empfunden

**Comment by kremin** [comment]
Ich würde das gerne mal mit reallem Inhalt testen.

**Comment by kremin** [comment]
siehe #18
