### ISSUE TITLE
mute button reel

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#11]
Kunde wünscht einen mute-button. lets talk.

**Comment by kremin** [comment]
kein problem. wo soll der hin?

**Comment by Matteng123** [comment]
![image](https://cloud.githubusercontent.com/assets/19430535/21603430/8f72f2f4-d19d-11e6-83e5-82c8c9168ddb.png)

hab dir das mal in die psd gemacht. ist mute/unmute drin. ich weiss nicht wie genau die die assets brauchst. kannst mir sagen oder eben selbst reingehen.

**Comment by kremin** [comment]
done
