### ISSUE TITLE
gabel-seite

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#12]
24-1 hatte schon vor etwas längerer zeit eine art gabelseite angefragt. soll genauso klappen wie die hier:
http://rankin.co.uk/

auswahl über buttons, mouseover zeigen den inhalt an. klick auf cinematography startet die seite mit scroll nach unten, click auf photographie geht auf http://claudiodilucia.com/

hintergrund ist der, daß es später auch noch eine 24-1 agency geben wird, also noch ein dritter bereich hinzukommt. ich hoffe das ist alles noch gut mit umsetzbar. wenn es an irgendeiner stelle wegen des layouts fuckup-mäßig wird sag bescheid. das layout ist auch nur für uns intern, das sollten wir dann über die preview-seite abstimmen. letz talk!

![image](https://cloud.githubusercontent.com/assets/19430535/21606982/6dfb9dea-d1b3-11e6-875d-b0cea078f052.png)

**Comment by Matteng123** [comment]
das ist jetzt quasi das "wunsch-layout" weil die das von der beispielseite haben. wenn das doof ist wegen weiss und logo nicht oben usw. passen wir das noch an.

PSD ist geupdated.

**Comment by kremin** [comment]
Ist kein problem. würde es aber genau wie bei rankin so machen, dass es eine eigenständige html seite ist es danach jeweils eine eigne URL gibt. von daher ist das hier einfach eine zusätzlich html page. wir müssen nur überlegen wie wir das mit der pflege machen. alles über ein backend?

**Comment by Matteng123** [comment]
update design:
![image](https://cloud.githubusercontent.com/assets/19430535/22147102/75bf4444-df07-11e6-857d-bba783c69c6c.png)

das soll noch einfacher werden. da die wörter wie bei rankin immer etwas anders sein sollen würde ich das als bild einbinden.

**Comment by kremin** [comment]
schickste mir die psd dazu pls

**Comment by Matteng123** [comment]
die wollen das ganze jetzt so geroutet haben:

1.) cinematography —> motionpicture.24-1.com
2.) photography —> claudiodilucia.com
3.) agency —> agency.24-1.com   

der letzte punkt wird noch kommen.

**Comment by Matteng123** [comment]
das ist das lezte abgestimmt layout. liegt auch in der PSD:

![image](https://cloud.githubusercontent.com/assets/19430535/23184432/0bd49b46-f880-11e6-84ad-27882190f26c.png)

**Comment by kremin** [comment]
in der psd liegt es mit schwarzer box und weißem logo. 
kann ich aber bei bedarf auch noch drehen:
http://24-1.matteng.de/gate.html

**Comment by Matteng123** [comment]
ah sorry, hast recht. die seite ging nochmal hin- und her. die version in der PSD ist die richtige. bitte nochmal nach dem logo schauen, da ist das motion-picture raus. auch die größe ist nochmal n bisschen anders. die wörter unten kommen nur auf mouseover. hatte das am anfang des threads mit drin. ist genau wie bei der rankin-seite

**Comment by kremin** [comment]
Und wie ist das bei mobile?

**Comment by kremin** [comment]
Aktualisiert. Jetzt fehlt nur noch der finale Text.
