### ISSUE TITLE
recht-links pfeil

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#16]
jetzt sollen doch wieder pfeile rein und die punkte raus ... pfeile aber nicht rechts-links am unteren rand verteilt. mein vorschlag wäre sie direkt neben das weiße drei-punkte-moped rechts zu packen. dann hätte man noch einen logischen zusammenhang.

gewünscht sind weiterhin keyboad-shortcuts für links und rechts. nach unten und oben wäre wahrscheinlich auch noch cool.

![image](https://cloud.githubusercontent.com/assets/19430535/21608934/e36f1a82-d1bf-11e6-869e-f7590fffa19d.png)

**Comment by kremin** [comment]
Done
