### ISSUE TITLE
Filter mechanismus 

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#18]
das mit dem rausfiltern lassen wir erstmal so und pflegen zunächst inhalte ein. 

falls die das dann doch geändert haben wollen: ich glaube hautp-schmerz ist das "dunkle". zudem finden sie nicht so gut, daß der name bei den weggefilterten items verschwindet. und sie haben noch bemängelt, daß man rausgefilterte items trotzdem anklicken kann (wäre für mich jetzt total nice to have).

ich mache mal einen layout-vorschlag dafür, wie weggefilterte items evtl. aussehen könnten. vielleicht finden wir mit der bisherigen technischen lösung ja noch nen ansatz der allen gefällt. 

![image](https://cloud.githubusercontent.com/assets/19430535/21609170/32b8210a-d1c1-11e6-9b91-6cf5d11503b6.png)

**Comment by kremin** [comment]
was hällst du von einem blurry bild oder einem pixelbild?

**Comment by Matteng123** [comment]
blurry kann ich mir auch sehr gut vorstellen. pixel passt glaube ich eher weniger. käme aber auch auf einen versuch an. wie wir schon besprochen hatten - ich finde die bewegung bei jedem klick zwar logisch richtig, da sich mit dem jetzigen content aber gefühlt nichts ändert (vor allem bei film) müsste man nochmal anwarten, wie das ankommt wenn noch weitere cases eingefügt werden. es wird noch ein paar mehr zu konzept geben.
