### ISSUE TITLE
2. video auf projektseiten

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#19]
es kam der wunsch auf mehrere videos auf den unterseiten einzubinden, da es auch making-of-videos gibt, die zum finalen video gezeigt werden sollen

wäre für mich aber eine anforderung, die gemacht wird wenn noch zeit über ist - auf jeden fall nach der "filter" systematik

**Comment by kremin** [comment]
Yoah. Kann ich ins moodboard aufnehmen. Ist einfach.

**Comment by kremin** [comment]
Done. Jetzt können die das Moodbaord mit Videos voll hauen.
