### ISSUE TITLE
externe url als menüpunkt

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#22]
claudio möchte noch "photography" als externen link in das menü haben. soll einfach _blank losgehen auf http://claudiodilucia.com/ 

habe keine möglcihkeit gefunden das einzupflegen evtl. habe ich sie aber auch einfach nur übersehen

**Comment by kremin** [comment]
Kein Problem ist fix getan.

**Comment by kremin** [comment]
Ich kann den Link da einbauen aber die Navi wird jetzt echt breit.

**Comment by kremin** [comment]
Doch nicht so easy. Aber habe das Thirdlevel Menu gemacht.
