### ISSUE TITLE
youtube skinning

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#24]
hatten wir ja schon kurz besprochen: gib mir nochmal ne einschätzung was das anzeitaufwand wäre. dann gebe ich das weiter.

**Comment by kremin** [comment]
4 std.

**Comment by Matteng123** [comment]
hab ich mal weitergeleitet!

**Comment by kremin** [comment]
machste design?

**Comment by Matteng123** [comment]
mach isch. freitag ;)

**Comment by Matteng123** [comment]
hier ist mein vorschlag. sag mal bescheid ob das realistisch ist. 24-1 hat es auch noch nicht gesehen.

![24-1_website_20170113_11_07_player](https://cloud.githubusercontent.com/assets/19430535/23267213/54a16032-f9ea-11e6-9154-df4b674beeb2.jpg)

**Comment by kremin** [comment]
kannst du den lautstärek regler rausnehmen. und nur mute/ton machen. 
Die meisten steuren die lautstärke am rechner oder an den boxen nicht im player und für mich ist das ein bißchen mehr aufwand. 

Wofür die Settings? Die Qualität wird anhand der Bandbreite gewählt. Immer das bestmöglich um bei ruckjelfreien abspielen. würde ich nicht auswählen lassen.

**Comment by Matteng123** [comment]
die version ist es geworden:

![24-1_website_20170113_11_07_player](https://cloud.githubusercontent.com/assets/19430535/23370308/8e4d733e-fd14-11e6-8708-04cdd81d3937.jpg)
