### ISSUE TITLE
weitere hintergrundebene für parallaxe

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#26]
die fanden deine idee mit dem hintergrund gut und würden das gern einmal sehen. anbei 2 testbilder.

![hintergrund](https://cloud.githubusercontent.com/assets/19430535/22145735/eae08698-df02-11e6-82c1-cbc0fdf512ca.jpg)
![person](https://cloud.githubusercontent.com/assets/19430535/22145734/eaddc980-df02-11e6-873c-6e5f8c96b19c.png)

**Comment by Matteng123** [comment]
das hier legen wir mal auf eis. der parallax-effekt ist ja eh quasi raus.

**Comment by Matteng123** [comment]
parallax bei der schrift soll jetzt ganz raus, dafür der effekt hier rein.

**Comment by kremin** [comment]
yeah.

**Comment by kremin** [comment]
Eingebaut

**Comment by Matteng123** [comment]
ist glaube ich nicht gepusht. bitte nochmal checken. bei team sieht alles genauso aus wie vorher - nur die parallaxe ist raus

**Comment by kremin** [comment]
Hehe ja klar. Die Bilder müssen gepflegt werden ;)
