### ISSUE TITLE
scrollverhalten bei filterung

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#29]
wenn man die work-liste weit runterscrollt und dann "concept" auswählt erhält man eine vermeintlich leere seite. die cases sind dann zu weit oben - man müsste hinscrollen.

wir hatten da ja auch schonmal drüber gesprochen, bin mir aber nicht sicher, ob es eine lösung dazu gab? lass uns dazu am besten mal telefonieren und abwägen. hatte zum glück auch keine prio der bug. war eher so ... ohjahm, nicht ganz optimal.

**Comment by kremin** [comment]
das fixe ich.

**Comment by kremin** [comment]
Done
