### ISSUE TITLE
team: bis zu 4 felder

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#3]
es soll möglich sein bis zu 4 felder mit infos anzulegen

- entweder fest positioniert
- oder frei positionierbar (x/y) je nachdem was einfacher ist

wahrscheinlich würden nie alle 4 felder genutzt, sondern dienen eher dazu variabler im umgang damit zu sein. bei spotlightthemovie.com sind die elemente auch an festen orten. die waren aber ganz offen wie wir das lösen.

**Comment by kremin** [comment]
ok, zur Zeit haben wir 3 + textbox, kann aber noch eine vierte ergänzen.
- die sind fix positioniert.

**Comment by Matteng123** [comment]
dann mach eine vierte rein und lass erstmal fix. im grunde ist man ja flexibel dadurch welche der 4 man benutzt. wenn das nicht reicht kann man immer nochmal schauen.

**Comment by kremin** [comment]
gab es eigentlich eine präferenz was die animation angeht?

**Comment by kremin** [comment]
wo soll ich die vierte hinballern?

**Comment by kremin** [comment]
könnte die aber auch frei per prozente positionierbar machen ist dann pro slide unterschiedlich und muss gepflegt werden ;)
dann gäbe es einmal h1-h4 pro slide

**Comment by Matteng123** [comment]
![image](https://cloud.githubusercontent.com/assets/19430535/22499536/bf3b692a-e85f-11e6-9849-d726bb61215c.png)

ich hatte da an unten rechts gedacht. frei positionierbar fände ich noch ne ausbaustufe. aber größen sind natürlich nice und ist - vermute ich mal - relativ schnell gemacht.

**Comment by kremin** [comment]
Done
