### ISSUE TITLE
kirby text in textboxen?

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#30]
wollte gerade einen google-maps link in die kontakt-box einfügen. ging leider nicht per kirby-text. welche möglichkeiten hattest du da eingeplant? würde was gegen kirbytext sprechen?

siehe dafür mein beispiel:
http://24-1.matteng.de/de/?section=kontakt

**Comment by kremin** [comment]
ne das passt. muss nur die ausgabe im template anpassen.

**Comment by kremin** [comment]
Done
