### ISSUE TITLE
film startet nicht vom anfang

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#34]
claudio meint der film startet nicht immer vom anfang. habs selber noch nicht nachvollzogen.

**Comment by kremin** [comment]
?? sobald er geladen ist startet er. Oder meint er, dass der Film einen Teil überspringt?

**Comment by kremin** [comment]
nach wie vor mit ?

**Comment by Matteng123** [comment]
habe da keine probleme. ist auch nicht nochmal angemerkt worden. closed.
