### ISSUE TITLE
safari bug

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#36]
![___](https://cloud.githubusercontent.com/assets/19430535/22525582/0562282c-e8c8-11e6-8ed1-20842810ecaf.png)
![1](https://cloud.githubusercontent.com/assets/19430535/22525584/0682b546-e8c8-11e6-9b5b-b84af98a4fbd.png)
![2](https://cloud.githubusercontent.com/assets/19430535/22525586/07841c5a-e8c8-11e6-95eb-b9812b1064a3.png)

die jungs haben irgendwie probleme mit dem safari. philipp hat auch den cache mal geleert, anscheinend geht nix. auch die navigation per tastatur geht leider nicht.

**Comment by kremin** [comment]
bei mir sieht es im safari nicht ganz so schlimm aus aber er hat auch seine macken. behebe ich.

**Comment by Matteng123** [comment]
heute kam nochmal die anfrage rein wann die bugs raus sind. wir müssen denen glaube ich nochmal nen zeitplan präsentieren.

**Comment by kremin** [comment]
Der sollte aber raus sein der bug.

**Comment by Matteng123** [comment]
auch mit der pfeiltasten-navi? geht das bei dir?

**Comment by kremin** [comment]
bei den tasten müsste ich wahrscheinlich nochmal die Keycodes durchtesten. Die können auf dem PC andere sein als beim Mac. Geht aber bei mir.

**Comment by Matteng123** [comment]
die haben die seite nochmal bei denen auf mehreren rechnern getestet, mit cache leeren etc. leider immer noch sehr zerschossen. der safari macht da seltsame sachen. bei meinem safari auf dem mac macht der der auch. scheint also wirklich ein eher übergeordnetes problem zu sein.

![5](https://cloud.githubusercontent.com/assets/19430535/23251475/cabb288a-f9ad-11e6-9680-58b37d237b7d.png)
![4](https://cloud.githubusercontent.com/assets/19430535/23251476/cabb44e6-f9ad-11e6-8269-40713defae3f.png)
![3](https://cloud.githubusercontent.com/assets/19430535/23251479/cabc195c-f9ad-11e6-8748-b6ba6bf5a007.png)
![2](https://cloud.githubusercontent.com/assets/19430535/23251478/cabbc60a-f9ad-11e6-9d04-2812ce4ea95a.png)
![1](https://cloud.githubusercontent.com/assets/19430535/23251477/cabb727c-f9ad-11e6-9d5f-958e907489a4.png)
![6](https://cloud.githubusercontent.com/assets/19430535/23251474/cabb1bd8-f9ad-11e6-8d4d-577703f8e6ad.png)

**Comment by kremin** [comment]
raff ich nicht. habe ich auf keinem safari. muss ich suchen.

**Comment by kremin** [comment]
Fixed mit -webkit css prefixe
