### ISSUE TITLE
scrollen auf der projektdetailseite "klemmt"

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#37]
wenn man auf einer projektdetailseite mit der maus über dem video ist und dann scrollt checkt er das nciht so richtig. er geht dann nicht ganz runter - es klappt erst, wenn man "an der seite" neben dem video scrollt. problematik kommt jetzt natürlich erst richtig raus, weil die video grösser sind.

**Comment by kremin** [comment]
Kann ich nicht rekonstruieren, weder safari noch Firefox.

**Comment by Matteng123** [comment]
ich kanns bei mir in allen browsern reproduzieren. zeig ich dir mal, was ich meine. ggs ein pc-bug. wenn überhaupt bug ;)

**Comment by kremin** [comment]
das kann ich nicht fixen. der iframe catcht den event.

**Comment by Matteng123** [comment]
wurde bis jetzt auch noch nicht angemerkt. von daher. closed.
