### ISSUE TITLE
editor hängt sich auf wenn die bilder zu gross sind

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#39]
sobald bilder, die eine gewisse abmessung überschreiten hochgeladen werden - hängt sich der editor auf und zeit nur noch eine weisse seite. anbei noch ein bild, was den editor zerlegt hat.
[studio.zip](https://github.com/youonlyliveonce/24-1/files/789712/studio.zip)

**Comment by kremin** [comment]
echt jetzt? 5600 px breite?

**Comment by kremin** [comment]
direkt mal eine crop function eingebaut damit die nicht mit 5000 px im vordergrund ankommen

**Comment by kremin** [comment]
Das ist ein Serverproblem bei dir. Local geht das und auf den Timmeservern auch. Du müsstest den PHP Memory hochdrehen. Wenn ich das per htaccess mache bekomme ich eine Servermdleung von deinem Provider. Das ist wahrscheinlich untersagt. :)

**Comment by Matteng123** [comment]
für mich auch zunächst closed. mal schauen was der server dazu sagt.
