### ISSUE TITLE
impressum

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#4]
wir müssen noch eine möglichkeit schaffen das impressum mit haftungsausschuss zu erstellen. wahrscheinlich wieder eine scroll-lösung

-> design folgt

**Comment by kremin** [comment]
wait on design

**Comment by Matteng123** [comment]
anbei ein design für reine textseiten. müssen mal wegen der zweispaltigkeitschauen wie wir das pflegbar machen oder ob wir es einfach weglassen. oben ist nun auch ein submenue für impressum etc. drin. habe auch alle anderen screens mal geupdatet um das zu testen.

check it out!

![image](https://cloud.githubusercontent.com/assets/19430535/21934240/fc4fc2a4-d9a8-11e6-89aa-8c0a8f26807f.png)

**Comment by kremin** [comment]
Done
