### ISSUE TITLE
schriftgröße "about" / für grosse monitore

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#41]
gerade bei der about-section gibt es immer relativ wenig text. das sieht bei den grossen monitoren immer eher doof aus. 

hast du da ne idee wie man das elegant lösen kann? schriftgröße > 1600px nochmal anheben, schriftgröße im backend "einstellen" durch kirbytext oder ...?

![image](https://cloud.githubusercontent.com/assets/19430535/23469799/f878f8b4-fea4-11e6-9ac0-529562f7b8d4.png)

**Comment by kremin** [comment]
Habe noch zwei Stufen eingebaut
