### ISSUE TITLE
parallaxe komplett raus - bis auf die team-member

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#44]
parallaxe fand claudio immer noch doof, leider. ich würd sie trotzdem nicht ganz rausmachen, aber auf jeden fall nochmal stark abschwächen. ggfs kommt die mit dem hintergrund wieder cooler.

**Comment by kremin** [comment]
Nur noch eine leichte Bewegung auf dem Hintergrundbild und wenn ein zusätzliches "Vordergrund-bild" eingefügt ist.
