### ISSUE TITLE
weitere abstufung für schrift

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#45]
auf meinem monitor ist auch die nochmal angepasste grösse immer noch zu klein. daher vorschlag schriftgrösse auf 1.8 em ab 19XX px rauf.

vorher:
![jetzte](https://cloud.githubusercontent.com/assets/19430535/23581624/6de2e64a-0117-11e7-8061-9f47fc5e3569.JPG)

nachher:
![2em](https://cloud.githubusercontent.com/assets/19430535/23581625/73210c5e-0117-11e7-9ca9-8ba6e0e88dae.JPG)

**Comment by Matteng123** [comment]
erster versuch war mit 2em, das war aber doch zu viel. 1.8 em wäre son mittelding.

**Comment by kremin** [comment]
Hatte noch nicht gepusht.

**Comment by kremin** [comment]
Jetzt.

**Comment by Matteng123** [comment]
sieht gut aus!
