### ISSUE TITLE
infos für gate-seite

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#49]
![image](https://cloud.githubusercontent.com/assets/19430535/23855388/ad4103d2-07f5-11e7-9832-11ff7142e5d6.png)

**Comment by Matteng123** [comment]
wenn unten etwas weniger infos drunter sind das ganze konstrukt etwas mehr in die mitte wäre super.

**Comment by kremin** [comment]
Den Strich mittig unter das Logo? Ok aber dann muss ich die Elemente gleich breit machen. Naja ich schua mal wie das geht
