### ISSUE TITLE
mobile: awards sitzen tief

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#54]
ipad hoch und phones würde ich die awards komplett weglassen. wenn das wenig aufwand ist einfach machen, dann stimme ich das parallel mit den 24-1s ab. wenn das mehr aufwand ist stimme ich das zuerst ab und dann wirds rausgeschmissen.

![image](https://cloud.githubusercontent.com/assets/19430535/23953141/04605e52-0994-11e7-914b-dc5747b2dfdc.png)

![image](https://cloud.githubusercontent.com/assets/19430535/23953187/21bd85ec-0994-11e7-8420-c8fefdb975ef.png)

am ipad quer ist das verschoben. hier etwas kleiner und höher.
![image](https://cloud.githubusercontent.com/assets/19430535/23953094/e24f0822-0993-11e7-8aab-fb22238f325a.png)

**Comment by kremin** [comment]
Gemacht
