### ISSUE TITLE
textbox "about" verschwindet

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#55]
das ein- und ausblenden der textboxen erzeugt beim scrollen auf den mobilen geräten zum teil komische effekte:

![image](https://cloud.githubusercontent.com/assets/19430535/23953319/87baea74-0994-11e7-8451-cdd03de184d4.png)

man schafft es leicht die texte auszublenden bzw. man denkt da ist nichts und auf einmal blendet sich der text ein. hier müsste man entweder den effekt-start anpassen oder die einblendung komplett weglassen.

**Comment by kremin** [comment]
Wenn die Section den Viewport verlässt wird ihr der aktiv status entzogen und damit blendet der text aus. Scrollst du wieder hoch kommt er zurück.

**Comment by Matteng123** [comment]
ok, dann lassen wir das erstmal so und warten ab ob dazu noch anmerkungen kommen.
