### ISSUE TITLE
neue kunden-seite

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#7]
kundenseite wird auch scollbar sein:

![image](https://cloud.githubusercontent.com/assets/19430535/21261041/5fe35352-c389-11e6-8eb8-c9f019c9faf1.png)

-> design wird noch angepasst: die kacheln sollen fast schwarz sein, logos weiss.

**Comment by kremin** [comment]
bliebt aber bei dem raster?

**Comment by Matteng123** [comment]
genau, raster bleibt!

**Comment by kremin** [comment]
kannste mir doe logos als einzelne pngs/jpgs schicken pls, dann mache ich diese seite fix

**Comment by Matteng123** [comment]
Logos haste - sind hässlich mit rändern und so - einfach nehmen. und kacheln dann schwazzz
