### ISSUE TITLE
ende der seite

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/24-1#8]
es soll ersichtlich sein, wenn man nicht mehr weiter nach unten scrollen kann. man also am ende der gesamten seite angekommen ist.

![image](https://cloud.githubusercontent.com/assets/19430535/21261073/8f1d85d4-c389-11e6-85a1-40705c0935e3.png)

**Comment by kremin** [comment]
ok. das muss ich noch machen. ist aber ein reines template issue.
